worker_processes 1;
daemon off;
error_log /dev/stderr warn;
pid /tmp/nginx.pid;

events {
    worker_connections 256;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log /dev/stdout;
    sendfile on;
    server_tokens off;

    server {
        listen 8080;
        server_name _;

        location /assets/resume/ {
            alias /srv/site/assets/resume/;
            add_header Cache-Control "no-cache";
        }

        location /assets/ {
            alias /srv/site/assets/;
            expires 7d;
        }

        location /css/ {
            alias /srv/site/css/;
            expires 1h;
        }

        location /js/ {
            alias /srv/site/js/;
            expires 1h;
        }

        location / {
            proxy_pass http://127.0.0.1:8000;
            proxy_set_header Host $host;
        }
    }
}
